name: Docker
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_TOKEN }}/demo-test:github-actions .
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_TOKEN }}/demo-test:github-actions